blank_lines_upper_bound = 2 
brace_style = "SameLineWhere"
color = "Always"
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 30
wrap_comments = true
